name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: develop

    - name: Install dependencies
      run: npm install

    - name: Build and test
      run: |
        npm run dev

    - name: Install PM2
      run: npm install -g pm2

    - name: Stop server with PM2
      run: pm2 stop index.js

    - name: Start server with PM2
      run: pm2 start index.js
